# Page settings
baseurl = "localhost:1313"
title = "JavaFX"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Navigation
  [params.navigation]
    brand = 'JavaFX'
    home = "Home"
    documentation = "Documentation"
    # events = "Upcoming Events"
    work = "Community"
    testimonials = "Testimonials"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

  # Hero section
  [params.hero]
    title = 'JavaFX 15'
    subtitle = 'OpenJFX is an open source, next generation client application platform for desktop, mobile and embedded systems built on Java.</br> It is a collaborative effort by many individuals and companies with the goal of producing a modern, efficient, and fully featured toolkit for developing rich client applications.</br></br>'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Download"
    description = 'The JavaFX 15 runtime is available as a platform-specifc SDK, as a number of jmods, and as a set of artifacts in Maven Central.'
    url = "https://gluonhq.com/products/javafx/"
    button = "Download"
    icon = "icon-cloud-download"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "OpenJFX is free software, licensed under the GPL with the class path exception, just like the OpenJDK."
    url = "https://github.com/openjdk/jfx"
    button = "Let's do it!"
    icon = "icon-social-github"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"

  # Documentation section
  [params.documentation]
    enable = true
    title = "Documentation"
    description = ""

    [[params.documentation.item]]
      title = "Release Notes"
      description = "Read about what is new in JavaFX 15"
      url = "https://github.com/openjdk/jfx/blob/jfx15/doc-files/release-notes-15.md"
      button = "Visit"
      icon = "icon-book-open"
      img = "img_7.jpg"

    [[params.documentation.item]]
      title = "Getting Started"
      description = "Get started quickly and easily with JavaFX 15"
      url = "/openjfx-docs/"
      button = "Visit"
      icon = "icon-book-open"
      img = "img_8.jpg"

    [[params.documentation.item]]
      title = "Javadoc"
      description = "API documentation for JavaFX 15"
      url = "/javadoc/15/"
      button = "Visit"
      icon = "icon-book-open"
      img = "img_10.jpg"

  # Events section
  #[params.events]
  #  enable = true
  #  title = "Upcoming Events"
  #  description = ""
  #  footertext= ""
  #
  #  [[params.events.row]]
  #    title = 'Oracle Code One'
  #    subtitle = "A new developer conference that's inclusive to more languages, technologies, and developer communities."
  #    dates = "October 22-25, 2018"
  #    url = "https://oracle.rainfocus.com/widget/oracle/oow18/catalogcodeone18?search=javafx"
  #    img = "oracle-code-one.png"
  #    alt = "Image2"
  #
  #  [[params.events.row]]
  #    title = 'Devoxx Belgium 2018'
  #    subtitle = "From Developers, For Developers!"
  #    dates = "November 12-16, 2018"
  #    url = "https://dvbe18.confinabox.com/search?q=javafx"
  #    img = "DevoxxLogo.png"
  #    alt = "Image2"
  #
  #  [[params.events.row]]
  #    title = 'JavaFX Days Zurich'
  #    subtitle = "A conference focused on the JavaFX technology for developing state-of-the-art desktop and mobile applications."
  #    dates = "December 3-5, 2018"
  #    url = "https://www.javafx-days.com/"
  #    img = "JavaFX-Days.png"
  #    alt = "Image2"


  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = ""

    [[params.testimonials.item]]
      quote = "&ldquo;I'm excited to see the more folks from the wider Java Community working together with Oracle on JavaFX. This release proves there is a great future for client-side Java development. As an OpenJDK Project , OpenJFX shares much of its principles and infrastructure, leading to a high-quality release that is very well aligned with the upcoming Java 11 release.&rdquo;"
      person = 'Georges Saab <span class="subtext">Vice President, Software Development, Java Platform Group at <a href="https://www.oracle.com/java/" target="_blank">Oracle</a></span>'
      img = "Saab.jpg"
      alt = "Georges Saab"

    [[params.testimonials.item]]
      quote = "&ldquo;I am very pleased with the unbundled OpenJFX 11 release, which is now available to developers via maven modules or a standalone SDK. This release is a great example of what can happen with a vibrant community of open-source developers. I look forward to the future of JavaFX as a community-driven project.&rdquo;"
      person = 'Kevin Rushforth <span class="subtext">OpenJFX Project Co-Lead, <a href="https://www.oracle.com/java/" target="_blank">Oracle</a></span>'
      img = "Rushforth.jpg"
      alt = "Kevin Rushforth"

    [[params.testimonials.item]]
      quote = "&ldquo;OpenJFX is like a child to me. After helping it to grow up for so long, I now look at it proudly and excited about its future. The community effort that is growing around it pleases me to no end, and I can't wait to see where it goes next.&rdquo;"
      person = 'Jonathan Giles <span class="subtext"><a href="http://jonathangiles.net/">Java guy</a> at Microsoft, OpenJFX contributor & <a href="http://controlsfx.org/" target="_blank">ControlsFX</a> project lead</span>'
      img = "jonathan.jpg"
      alt = "Jonathan Giles"

    [[params.testimonials.item]]
      quote = "&ldquo;As an advocate of JavaFX for over a decade I'm thrilled about the community support and momentum of OpenJFX. A big thanks to the folks at Gluon for providing leadership to the OpenJFX effort!&rdquo;"
      person = 'James Weaver <span class="subtext">Developer advocate at <a href="https://pivotal.io/" target="_blank">Pivotal</a></span>'
      img = "weaver.jpg"
      alt = "James Weaver"

    [[params.testimonials.item]]
      quote = "&ldquo;For me OpenJFX represents a major milestone in the ongoing effort to make JavaFX the leading technology for mobile, embedded, and desktop applications. Finally Java has an advanced UI toolkit that can evolve independently of JDK development activities. A toolkit that is supported by a passionate developer community where each member can directly contribute to its future!&rdquo;"
      person = 'Dirk Lemmermann <span class="subtext">CEO of <a href="https://dlsc.com" target="_blank">DLSC Software & Consulting GmbH</a></span>'
      img = "Lemmermann.jpg"
      alt = "Dirk Lemmermann"

    [[params.testimonials.item]]
      quote = "&ldquo;JavaFX is a fantastic technology that has enabled the cost-effective development of capabilities while providing performance and customization necessary for our engineering problems. OpenJFX 11 is a big step forward that streamlines our application images, making them more lightweight. This makes distribution to our users performing design analysis supporting NASA missions easy so they can move forward faster.&rdquo;"
      person = 'Sean Phillips <span class="subtext">Software Architect for the Deep Space Trajectory Explorer at <a href="https://ai-solutions.com/" target="_blank">a.i. solutions</a></span>'
      img = "sean.jpg"
      alt = "Sean Phillips"

    [[params.testimonials.item]]
      quote = "&ldquo;At KBC, we use JavaFX in a number of projects. We are extremely happy to see that the JavaFX project is moving forward. The open development in OpenJFX ensures that different companies can provide their input, which typically results in high-quality releases.&rdquo;"
      person = 'Lieven Franckaert <span class="subtext">Project Leader at <a href="https://www.kbc.com/en" target="_blank">KBC Bank</a></span>'
      img = "person1.jpg"
      alt = "KBC"

    [[params.testimonials.item]]
      quote = "&ldquo;I'm very optimistic about JavaFX 11 and beyond. The excellent technical work, including hardware acceleration and first class Java API's are now combined with modern, open development, testing and integration approaches. The input of new contributors is already showing.&rdquo;"
      person = 'Johan Vos <span class="subtext">OpenJFX Project Co-Lead, Co-founder at <a href="https://gluonhq.com/" target="_blank">Gluon</a></span>'
      img = "JohanVos.jpg"
      alt = "Johan Vos"

    [[params.testimonials.item]]
      quote = "&ldquo;JavaFX helps us provide the best solution for our customers, and with the new JavaFX 11 we will be even better than before. Thus, we have already started to migrate our projects. As a developer, it is fun to design JavaFX products with all the new potential and options it gives to enhance the customer experience.&rdquo;"
      person = 'Diego Cirujano Cuesta <span class="subtext"><a href="https://www.zeiss.com/" target="_blank">Zeiss</a> Expert Leader - Staff</span>'
      img = "diego.jpg"
      alt = "Diego Cirujano Cuesta"

  # Work section
  [params.work]
    enable = true
    title = "Community"
    description = "JavaFX features a vibrant and passionate developer community. This enthusiasm can be found in the <a href='http://mail.openjdk.java.net/mailman/listinfo/openjfx-dev' target='_blank'>open source mailing list</a>. Here are a few examples of tools and frameworks already supporting JavaFX 15."
    footertext = ''

    [[params.work.row]]
      img = "FlexGanttFX.png"
      alt = "Image2"
      title = 'FlexGanttFX'
      subtitle = 'A library for rendering Gantt charts in JavaFX'
      url = "https://dlsc.com/products/flexganttfx/"

    [[params.work.row]]
      img = "GluonMaps-1024x592@2x.png"
      alt = "Gluon Maps"
      title = "Gluon Maps"
      subtitle = "Tiles based geo-location map framework"
      url = "https://gluonhq.com/labs/maps/"

    [[params.work.row]]
      img = "ControlsFX.png"
      alt = "ControlsFX"
      title = "ControlsFX"
      subtitle = "De-facto JavaFX controls library"
      url = "http://controlsfx.org/"

    [[params.work.row]]
      img = "fxyz.png"
      alt = "FXyz"
      title = "FXyz project"
      subtitle = "3D Visualization and Components library"
      url = "https://github.com/FXyz/FXyz"

    [[params.work.row]]
      img = "dste.jpg"
      alt = "The Deep Space Trajectory Explorer"
      title = "DSTE"
      subtitle = "The Deep Space Trajectory Explorer"
      url = "https://ai-solutions.com/deep-space-trajectory-explorer/"

    [[params.work.row]]
      img = "ObjectGraphVisualizer.png"
      alt = "Object Graph Visualizer"
      title = "Object Graph Visualizer 3.2"
      subtitle = "A tool for to understand the Object Oriented paradigm and patterns"
      url = "https://github.com/Nurtak/ObjectGraphVisualization"

    [[params.work.row]]
      img = "CalendarFX.png"
      alt = "CalendarFX"
      title = "CalendarFX"
      subtitle = "A Java framework for creating sophisticated calendar views"
      url = "https://github.com/dlemmermann/CalendarFX"

    [[params.work.row]]
      img = "FormsFX.png"
      alt = "FormsFX"
      title = "FormsFX"
      subtitle = "A framework for easily creating forms for a JavaFX application."
      url = "https://github.com/dlemmermann/FormsFX"

    [[params.work.row]]
      img = "XR3Player.png"
      alt = "XR3Player"
      title = "XR3Player"
      subtitle = "Powerful JavaFX Media Player + Web Browser ."
      url = "https://github.com/goxr3plus/XR3Player"

    [[params.work.row]]
      img = "BootstrapFX.png"
      alt = "BootstrapFX"
      title = "BootstrapFX"
      subtitle = "Twitter's Bootstrap CSS for JavaFX"
      url = "https://github.com/aalmiray/bootstrapfx"

    [[params.work.row]]
      img = "Ikonli.png"
      alt = "Ikonli"
      title = "Ikonli"
      subtitle = "Font icon packs for JavaFX applications"
      url = "https://github.com/aalmiray/ikonli"

    [[params.work.row]]
      img = "TilesFX.png"
      alt = "TilesFX"
      title = "TilesFX"
      subtitle = "A JavaFX library containing tiles for Dashboards"
      url = "https://github.com/HanSolo/tilesfx"
      
    [[params.work.row]]
      img = "FXGL.jpg"
      alt = "FXGL"
      title = "FXGL"
      subtitle = "JavaFX game engine"
      url = "https://github.com/AlmasB/FXGL"

  # Services section
  [params.services]
    enable = false
    title = "Community"
    description = "JavaFX features a vibrant and passionate developer community. This enthusiasm can be found in the open source mailing list, the forum discussions. Here just some of the examples of tools and frameworks already supporting JavaFX 15"

    [[params.services.item]]
      title = '<a href="https://dlsc.com/products/flexganttfx/" target="_blank">FlexGanttFX</a>'
      description = 'FlexGanttFX is the most advanced JavaFX-based Gantt charting framework currently available for Java. It uses a very high abstraction level, which allows it to be applied in various and often very different domains such as ERP systems, production planning and scheduling applications, manufacturing execution systems or project portfolio management applications. FlexGanttFX and its predecessor frameworks FlexGantt (for Swing) and DJT have been used and tested by hundreds of professional planning and scheduling applications. The customer list contains companies such as Siemens, Boeing, NASA, JPL, Lockhead Martin, Raytheon, Kuehne + Nagel, SAIC, General Dynamics, ABAS, Bauer, etc…'
      icon = "icon-layers"

    [[params.services.item]]
      title = '<a href="https://gluonhq.com/labs/maps/" target="_blank">Gluon Maps</a>'
      description = "Gluon Maps is built with high performance in mind, but that doesn’t mean functionality is missing. Gluon Maps offers layer overlays, multiple tilesets, and much more."
      icon = "icon-map"

    #[[params.services.item]]
    #  title = "Photo &amp; Video"
    #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in #Bookmarksgrove right at the coast of the Semantics, a large language ocean"
    #  icon = "icon-video2"

    #  [[params.services.item]]
    #  title = "CMS &amp; eCommerce"
    #  description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in #Bookmarksgrove right at the coast of the Semantics, a large language ocean"
    #  icon = "icon-monitor"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = false
    map = true
    form = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '<br ><a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br /><br />This website is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.'
    #target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a #href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" #target="_blank">saey55</a>'
    #links = [
    #    ["icon-twitter", "#twitter"],
    #    ["icon-facebook", "#facebook"],
    #    ["icon-youtube", "#youtube"]
    #  ]
